In [11]:
import yaml 
import pickle
import glob 
import pandas as pd
files = glob.glob("*.yaml")
print(f"実験結果数 : {len(files)}")

version = "2010"
with open(f'../../data/Hazumi_features/Hazumi{version}_features.pkl', mode='rb') as f:
    SS, SS_binary, SS_ternary, TS, TS_binary, TS_ternary, SP, TP, Text, Audio, Visual, vid \
        = pickle.load(f, encoding='utf-8')

def profiling(profile, id, TP=None):
    age = int(id[5])
    gender = id[4]

    age_th = 3

    if profile == 0:
        res = 0
    elif profile == 1:
        # 性別
        if gender == 'F':
            res = 0
        else:
            res = 1
    elif profile == 2:
        # 年齢(2クラス)
        # 40 <=, 40 >
        if age <= age_th:
            res = 0
        else:
            res = 1
    elif profile == 3:
        if gender == 'F':
            if age <= age_th:
                res = 0 
            else:
                res = 1
        else:
            if age <= age_th:
                res = 2
            else:
                res = 3
    elif profile == 4:
        res = 1 if TP[id][0] >= 8 else 0
    elif profile == 5:
        res = 1 if TP[id][1] >= 8 else 0
    elif profile == 6:
        res = 1 if TP[id][2] >= 8 else 0
    elif profile == 7:
        res = 1 if TP[id][3] >= 8 else 0
    elif profile == 8:
        res = 1 if TP[id][4] >= 8 else 0
    return res

実験結果数 : 35

# TS & ternary

In [12]:
df_results = pd.DataFrame(0, index=[0,1,2,3,4,5,6,7,8], columns=['t','a','v','ta','tv','av','tav'])
for file in files:
    with open(file) as file:
        obj = yaml.safe_load(file)
        config = obj["config"]
        if config["annot"] == "TS" and config["label"] == "ternary":
            results = obj["results"]
            data = list(results.values())
            acc = round(sum(data) / len(data), 3)
            df_results.at[config['pmode'], config['modal']] = acc

display(df_results)

       t      a      v     ta     tv     av    tav
0  0.000  0.000  0.000  0.000  0.000  0.000  0.000
1  0.000  0.000  0.000  0.000  0.000  0.000  0.000
2  0.000  0.000  0.000  0.000  0.000  0.000  0.000
3  0.000  0.000  0.000  0.000  0.000  0.000  0.000
4  0.788  0.803  0.714  0.820  0.788  0.801  0.827
5  0.792  0.767  0.600  0.817  0.791  0.751  0.816
6  0.790  0.768  0.600  0.815  0.791  0.744  0.815
7  0.780  0.756  0.710  0.792  0.781  0.737  0.797
8  0.789  0.802  0.668  0.825  0.793  0.809  0.830

### 性別

In [13]:
# 女性
df_results = pd.DataFrame(0, index=[0,1,2,3,4,5,6,7,8], columns=['t','a','v','ta','tv','av','tav'])
for file in files:
    with open(file) as file:
        obj = yaml.safe_load(file)
        config = obj["config"]
        if config["annot"] == "TS" and config["label"] == "ternary":
            # results = obj["results"]
            results = []
            for key, data in obj["results"].items():
                if profiling(1, key) == 0:
                    results.append(data)
            acc = round(sum(results) / len(results), 3)
            df_results.at[config['pmode'], config['modal']] = acc
print("女性")
display(df_results)

# 男性
df_results = pd.DataFrame(0, index=[0,1,2,3,4,5,6,7,8], columns=['t','a','v','ta','tv','av','tav'])
for file in files:
    with open(file) as file:
        obj = yaml.safe_load(file)
        config = obj["config"]
        if config["annot"] == "TS" and config["label"] == "ternary":
            # results = obj["results"]
            results = []
            for key, data in obj["results"].items():
                if profiling(1, key) == 1:
                    results.append(data)
            acc = round(sum(results) / len(results), 3)
            df_results.at[config['pmode'], config['modal']] = acc
print("男性")
display(df_results)

女性

       t      a      v     ta     tv     av    tav
0  0.000  0.000  0.000  0.000  0.000  0.000  0.000
1  0.000  0.000  0.000  0.000  0.000  0.000  0.000
2  0.000  0.000  0.000  0.000  0.000  0.000  0.000
3  0.000  0.000  0.000  0.000  0.000  0.000  0.000
4  0.777  0.815  0.717  0.827  0.778  0.810  0.832
5  0.782  0.774  0.578  0.813  0.782  0.758  0.814
6  0.779  0.763  0.578  0.815  0.780  0.745  0.815
7  0.782  0.785  0.713  0.813  0.777  0.775  0.820
8  0.774  0.808  0.657  0.820  0.777  0.813  0.826

男性

       t      a      v     ta     tv     av    tav
0  0.000  0.000  0.000  0.000  0.000  0.000  0.000
1  0.000  0.000  0.000  0.000  0.000  0.000  0.000
2  0.000  0.000  0.000  0.000  0.000  0.000  0.000
3  0.000  0.000  0.000  0.000  0.000  0.000  0.000
4  0.798  0.791  0.712  0.813  0.798  0.793  0.823
5  0.801  0.760  0.620  0.821  0.800  0.745  0.817
6  0.799  0.773  0.620  0.816  0.801  0.742  0.815
7  0.778  0.729  0.708  0.772  0.785  0.701  0.776
8  0.803  0.797  0.679  0.831  0.808  0.806  0.835

### 年齢

In [14]:
# 50歳未満
df_results = pd.DataFrame(0, index=[0,1,2,3,4,5,6,7,8], columns=['t','a','v','ta','tv','av','tav'])
for file in files:
    with open(file) as file:
        obj = yaml.safe_load(file)
        config = obj["config"]
        if config["annot"] == "TS" and config["label"] == "ternary":
            # results = obj["results"]
            results = []
            for key, data in obj["results"].items():
                if profiling(2, key) == 0:
                    results.append(data)
            acc = round(sum(results) / len(results), 3)
            df_results.at[config['pmode'], config['modal']] = acc
print("50歳未満")
display(df_results)

# 50歳以上
df_results = pd.DataFrame(0, index=[0,1,2,3,4,5,6,7,8], columns=['t','a','v','ta','tv','av','tav'])
for file in files:
    with open(file) as file:
        obj = yaml.safe_load(file)
        config = obj["config"]
        if config["annot"] == "TS" and config["label"] == "ternary":
            # results = obj["results"]
            results = []
            for key, data in obj["results"].items():
                if profiling(2, key) == 1:
                    results.append(data)
            acc = round(sum(results) / len(results), 3)
            df_results.at[config['pmode'], config['modal']] = acc
print("50歳以上")
display(df_results)

50歳未満

       t      a      v     ta     tv     av    tav
0  0.000  0.000  0.000  0.000  0.000  0.000  0.000
1  0.000  0.000  0.000  0.000  0.000  0.000  0.000
2  0.000  0.000  0.000  0.000  0.000  0.000  0.000
3  0.000  0.000  0.000  0.000  0.000  0.000  0.000
4  0.777  0.787  0.719  0.805  0.776  0.783  0.813
5  0.779  0.732  0.592  0.797  0.778  0.719  0.792
6  0.777  0.731  0.592  0.794  0.778  0.702  0.796
7  0.774  0.745  0.724  0.777  0.778  0.718  0.788
8  0.771  0.784  0.648  0.807  0.774  0.790  0.813

50歳以上

       t      a      v     ta     tv     av    tav
0  0.000  0.000  0.000  0.000  0.000  0.000  0.000
1  0.000  0.000  0.000  0.000  0.000  0.000  0.000
2  0.000  0.000  0.000  0.000  0.000  0.000  0.000
3  0.000  0.000  0.000  0.000  0.000  0.000  0.000
4  0.800  0.821  0.709  0.837  0.804  0.823  0.845
5  0.807  0.808  0.609  0.843  0.807  0.791  0.844
6  0.805  0.813  0.609  0.840  0.806  0.794  0.837
7  0.787  0.769  0.694  0.809  0.785  0.759  0.809
8  0.811  0.824  0.692  0.848  0.815  0.833  0.851

In [15]:
# < 8
df_results = pd.DataFrame(0, index=[0,1,2,3,4,5,6,7,8], columns=['t','a','v','ta','tv','av','tav'])
for file in files:
    with open(file) as file:
        obj = yaml.safe_load(file)
        print(obj)
        config = obj["config"]
        if config["annot"] == "TS" and config["label"] == "ternary":
            # results = obj["results"]
            results = []
            for key, data in obj["results"].items():
                if profiling(4, key, TP) == 0:
                    results.append(data)
            acc = round(sum(results) / len(results), 3)
            df_results.at[config['pmode'], config['modal']] = acc
print("50歳未満")
display(df_results)

# 8 <=
df_results = pd.DataFrame(0, index=[0,1,2,3,4,5,6,7,8], columns=['t','a','v','ta','tv','av','tav'])
for file in files:
    with open(file) as file:
        obj = yaml.safe_load(file)
        config = obj["config"]
        if config["annot"] == "TS" and config["label"] == "ternary":
            # results = obj["results"]
            results = []
            for key, data in obj["results"].items():
                if profiling(4, key, TP) == 1:
                    results.append(data)
            acc = round(sum(results) / len(results), 3)
            df_results.at[config['pmode'], config['modal']] = acc
print("50歳以上")
display(df_results)

{'config': {'annot': 'TS', 'label': 'ternary', 'modal': 'tav', 'pmode': 7}, 'results': {'2010F2002': 0.869, '2010F2003': 0.804, '2010F2004': 0.725, '2010F3001': 0.673, '2010F3002': 0.656, '2010F3003': 0.872, '2010F3004': 0.905, '2010F4001': 0.844, '2010F4002': 0.844, '2010F4003': 0.877, '2010F4004': 0.846, '2010F4005': 0.837, '2010F4006': 0.802, '2010F5001': 0.848, '2010F5002': 0.882, '2010F5003': 0.831, '2010M2001': 0.851, '2010M2003': 0.68, '2010M2004': 0.915, '2010M2005': 0.753, '2010M2006': 0.929, '2010M3001': 0.833, '2010M3002': 0.845, '2010M3003': 0.817, '2010M3004': 0.757, '2010M3005': 0.67, '2010M3006': 0.621, '2010M4001': 0.875, '2010M4002': 0.848, '2010M4003': 0.667, '2010M5001': 0.887, '2010M5002': 0.432, '2010M6001': 0.818}}
{'config': {'annot': 'TS', 'label': 'ternary', 'modal': 'av', 'pmode': 5}, 'results': {'2010F2002': 0.821, '2010F2003': 0.657, '2010F2004': 0.712, '2010F3001': 0.634, '2010F3002': 0.689, '2010F3003': 0.782, '2010F3004': 0.676, '2010F4001': 0.75, '2010F4002': 0.781, '2010F4003': 0.877, '2010F4004': 0.699, '2010F4005': 0.761, '2010F4006': 0.779, '2010F5001': 0.861, '2010F5002': 0.868, '2010F5003': 0.783, '2010M2001': 0.724, '2010M2003': 0.67, '2010M2004': 0.732, '2010M2005': 0.742, '2010M2006': 0.894, '2010M3001': 0.773, '2010M3002': 0.66, '2010M3003': 0.768, '2010M3004': 0.743, '2010M3005': 0.583, '2010M3006': 0.68, '2010M4001': 0.833, '2010M4002': 0.641, '2010M4003': 0.794, '2010M5001': 0.859, '2010M5002': 0.784, '2010M6001': 0.788}}
{'config': {'annot': 'TS', 'label': 'ternary', 'modal': 'v', 'pmode': 5}, 'results': {'2010F2002': 0.667, '2010F2003': 0.667, '2010F2004': 0.55, '2010F3001': 0.317, '2010F3002': 0.489, '2010F3003': 0.474, '2010F3004': 0.703, '2010F4001': 0.609, '2010F4002': 0.698, '2010F4003': 0.642, '2010F4004': 0.374, '2010F4005': 0.728, '2010F4006': 0.488, '2010F5001': 0.671, '2010F5002': 0.574, '2010F5003': 0.59, '2010M2001': 0.621, '2010M2003': 0.454, '2010M2004': 0.659, '2010M2005': 0.602, '2010M2006': 0.859, '2010M3001': 0.576, '2010M3002': 0.629, '2010M3003': 0.695, '2010M3004': 0.643, '2010M3005': 0.427, '2010M3006': 0.621, '2010M4001': 0.625, '2010M4002': 0.728, '2010M4003': 0.667, '2010M5001': 0.521, '2010M5002': 0.432, '2010M6001': 0.788}}
{'config': {'annot': 'TS', 'label': 'ternary', 'modal': 'ta', 'pmode': 7}, 'results': {'2010F2002': 0.857, '2010F2003': 0.804, '2010F2004': 0.725, '2010F3001': 0.663, '2010F3002': 0.622, '2010F3003': 0.859, '2010F3004': 0.878, '2010F4001': 0.828, '2010F4002': 0.844, '2010F4003': 0.877, '2010F4004': 0.846, '2010F4005': 0.837, '2010F4006': 0.814, '2010F5001': 0.835, '2010F5002': 0.868, '2010F5003': 0.843, '2010M2001': 0.828, '2010M2003': 0.691, '2010M2004': 0.915, '2010M2005': 0.731, '2010M2006': 0.929, '2010M3001': 0.833, '2010M3002': 0.845, '2010M3003': 0.817, '2010M3004': 0.743, '2010M3005': 0.67, '2010M3006': 0.583, '2010M4001': 0.875, '2010M4002': 0.859, '2010M4003': 0.667, '2010M5001': 0.887, '2010M5002': 0.432, '2010M6001': 0.818}}
{'config': {'annot': 'TS', 'label': 'ternary', 'modal': 'tv', 'pmode': 5}, 'results': {'2010F2002': 0.762, '2010F2003': 0.843, '2010F2004': 0.725, '2010F3001': 0.644, '2010F3002': 0.567, '2010F3003': 0.936, '2010F3004': 0.892, '2010F4001': 0.797, '2010F4002': 0.854, '2010F4003': 0.877, '2010F4004': 0.821, '2010F4005': 0.826, '2010F4006': 0.791, '2010F5001': 0.646, '2010F5002': 0.662, '2010F5003': 0.867, '2010M2001': 0.851, '2010M2003': 0.732, '2010M2004': 0.915, '2010M2005': 0.731, '2010M2006': 0.918, '2010M3001': 0.894, '2010M3002': 0.866, '2010M3003': 0.866, '2010M3004': 0.614, '2010M3005': 0.709, '2010M3006': 0.544, '2010M4001': 0.917, '2010M4002': 0.87, '2010M4003': 0.778, '2010M5001': 0.859, '2010M5002': 0.614, '2010M6001': 0.924}}
{'config': {'annot': 'TS', 'label': 'ternary', 'modal': 'tav', 'pmode': 4}, 'results': {'2010F2002': 0.869, '2010F2003': 0.863, '2010F2004': 0.75, '2010F3001': 0.683, '2010F3002': 0.733, '2010F3003': 0.923, '2010F3004': 0.892, '2010F4001': 0.828, '2010F4002': 0.844, '2010F4003': 0.877, '2010F4004': 0.789, '2010F4005': 0.837, '2010F4006': 0.779, '2010F5001': 0.899, '2010F5002': 0.868, '2010F5003': 0.88, '2010M2001': 0.897, '2010M2003': 0.732, '2010M2004': 0.915, '2010M2005': 0.72, '2010M2006': 0.941, '2010M3001': 0.879, '2010M3002': 0.887, '2010M3003': 0.89, '2010M3004': 0.757, '2010M3005': 0.68, '2010M3006': 0.621, '2010M4001': 0.903, '2010M4002': 0.859, '2010M4003': 0.825, '2010M5001': 0.873, '2010M5002': 0.716, '2010M6001': 0.894}}
{'config': {'annot': 'TS', 'label': 'ternary', 'modal': 't', 'pmode': 4}, 'results': {'2010F2002': 0.762, '2010F2003': 0.863, '2010F2004': 0.738, '2010F3001': 0.663, '2010F3002': 0.567, '2010F3003': 0.936, '2010F3004': 0.878, '2010F4001': 0.781, '2010F4002': 0.854, '2010F4003': 0.877, '2010F4004': 0.732, '2010F4005': 0.848, '2010F4006': 0.791, '2010F5001': 0.646, '2010F5002': 0.662, '2010F5003': 0.831, '2010M2001': 0.839, '2010M2003': 0.742, '2010M2004': 0.927, '2010M2005': 0.731, '2010M2006': 0.941, '2010M3001': 0.879, '2010M3002': 0.866, '2010M3003': 0.854, '2010M3004': 0.614, '2010M3005': 0.66, '2010M3006': 0.534, '2010M4001': 0.917, '2010M4002': 0.88, '2010M4003': 0.794, '2010M5001': 0.845, '2010M5002': 0.614, '2010M6001': 0.924}}
{'config': {'annot': 'TS', 'label': 'ternary', 'modal': 'av', 'pmode': 8}, 'results': {'2010F2002': 0.881, '2010F2003': 0.882, '2010F2004': 0.688, '2010F3001': 0.653, '2010F3002': 0.811, '2010F3003': 0.705, '2010F3004': 0.865, '2010F4001': 0.828, '2010F4002': 0.792, '2010F4003': 0.827, '2010F4004': 0.772, '2010F4005': 0.859, '2010F4006': 0.791, '2010F5001': 0.899, '2010F5002': 0.868, '2010F5003': 0.88, '2010M2001': 0.897, '2010M2003': 0.711, '2010M2004': 0.854, '2010M2005': 0.753, '2010M2006': 0.894, '2010M3001': 0.788, '2010M3002': 0.804, '2010M3003': 0.829, '2010M3004': 0.786, '2010M3005': 0.65, '2010M3006': 0.767, '2010M4001': 0.903, '2010M4002': 0.772, '2010M4003': 0.81, '2010M5001': 0.873, '2010M5002': 0.75, '2010M6001': 0.864}}
{'config': {'annot': 'TS', 'label': 'ternary', 'modal': 'tv', 'pmode': 4}, 'results': {'2010F2002': 0.762, '2010F2003': 0.863, '2010F2004': 0.712, '2010F3001': 0.653, '2010F3002': 0.567, '2010F3003': 0.923, '2010F3004': 0.865, '2010F4001': 0.797, '2010F4002': 0.844, '2010F4003': 0.889, '2010F4004': 0.772, '2010F4005': 0.859, '2010F4006': 0.802, '2010F5001': 0.646, '2010F5002': 0.662, '2010F5003': 0.831, '2010M2001': 0.862, '2010M2003': 0.742, '2010M2004': 0.927, '2010M2005': 0.72, '2010M2006': 0.941, '2010M3001': 0.894, '2010M3002': 0.866, '2010M3003': 0.854, '2010M3004': 0.629, '2010M3005': 0.65, '2010M3006': 0.534, '2010M4001': 0.903, '2010M4002': 0.88, '2010M4003': 0.762, '2010M5001': 0.859, '2010M5002': 0.625, '2010M6001': 0.924}}
{'config': {'annot': 'TS', 'label': 'ternary', 'modal': 'v', 'pmode': 7}, 'results': {'2010F2002': 0.75, '2010F2003': 0.794, '2010F2004': 0.612, '2010F3001': 0.703, '2010F3002': 0.689, '2010F3003': 0.769, '2010F3004': 0.865, '2010F4001': 0.75, '2010F4002': 0.719, '2010F4003': 0.753, '2010F4004': 0.553, '2010F4005': 0.772, '2010F4006': 0.535, '2010F5001': 0.747, '2010F5002': 0.735, '2010F5003': 0.663, '2010M2001': 0.816, '2010M2003': 0.67, '2010M2004': 0.78, '2010M2005': 0.624, '2010M2006': 0.894, '2010M3001': 0.652, '2010M3002': 0.691, '2010M3003': 0.768, '2010M3004': 0.671, '2010M3005': 0.544, '2010M3006': 0.738, '2010M4001': 0.764, '2010M4002': 0.783, '2010M4003': 0.667, '2010M5001': 0.718, '2010M5002': 0.432, '2010M6001': 0.818}}
{'config': {'annot': 'TS', 'label': 'ternary', 'modal': 'a', 'pmode': 6}, 'results': {'2010F2002': 0.869, '2010F2003': 0.735, '2010F2004': 0.7, '2010F3001': 0.317, '2010F3002': 0.711, '2010F3003': 0.821, '2010F3004': 0.77, '2010F4001': 0.812, '2010F4002': 0.802, '2010F4003': 0.864, '2010F4004': 0.764, '2010F4005': 0.804, '2010F4006': 0.756, '2010F5001': 0.873, '2010F5002': 0.882, '2010F5003': 0.723, '2010M2001': 0.793, '2010M2003': 0.711, '2010M2004': 0.768, '2010M2005': 0.72, '2010M2006': 0.894, '2010M3001': 0.742, '2010M3002': 0.784, '2010M3003': 0.793, '2010M3004': 0.771, '2010M3005': 0.573, '2010M3006': 0.68, '2010M4001': 0.847, '2010M4002': 0.804, '2010M4003': 0.794, '2010M5001': 0.873, '2010M5002': 0.795, '2010M6001': 0.803}}
{'config': {'annot': 'TS', 'label': 'ternary', 'modal': 'av', 'pmode': 7}, 'results': {'2010F2002': 0.845, '2010F2003': 0.716, '2010F2004': 0.712, '2010F3001': 0.634, '2010F3002': 0.7, '2010F3003': 0.833, '2010F3004': 0.797, '2010F4001': 0.797, '2010F4002': 0.792, '2010F4003': 0.864, '2010F4004': 0.707, '2010F4005': 0.783, '2010F4006': 0.756, '2010F5001': 0.873, '2010F5002': 0.897, '2010F5003': 0.687, '2010M2001': 0.713, '2010M2003': 0.649, '2010M2004': 0.744, '2010M2005': 0.699, '2010M2006': 0.894, '2010M3001': 0.727, '2010M3002': 0.588, '2010M3003': 0.744, '2010M3004': 0.743, '2010M3005': 0.563, '2010M3006': 0.631, '2010M4001': 0.819, '2010M4002': 0.685, '2010M4003': 0.667, '2010M5001': 0.817, '2010M5002': 0.432, '2010M6001': 0.803}}
{'config': {'annot': 'TS', 'label': 'ternary', 'modal': 'tav', 'pmode': 8}, 'results': {'2010F2002': 0.869, '2010F2003': 0.873, '2010F2004': 0.7, '2010F3001': 0.673, '2010F3002': 0.778, '2010F3003': 0.821, '2010F3004': 0.905, '2010F4001': 0.828, '2010F4002': 0.833, '2010F4003': 0.889, '2010F4004': 0.748, '2010F4005': 0.87, '2010F4006': 0.814, '2010F5001': 0.886, '2010F5002': 0.868, '2010F5003': 0.855, '2010M2001': 0.908, '2010M2003': 0.711, '2010M2004': 0.915, '2010M2005': 0.753, '2010M2006': 0.929, '2010M3001': 0.848, '2010M3002': 0.835, '2010M3003': 0.915, '2010M3004': 0.771, '2010M3005': 0.68, '2010M3006': 0.757, '2010M4001': 0.903, '2010M4002': 0.88, '2010M4003': 0.825, '2010M5001': 0.873, '2010M5002': 0.795, '2010M6001': 0.894}}
{'config': {'annot': 'TS', 'label': 'ternary', 'modal': 't', 'pmode': 6}, 'results': {'2010F2002': 0.762, '2010F2003': 0.863, '2010F2004': 0.712, '2010F3001': 0.644, '2010F3002': 0.556, '2010F3003': 0.936, '2010F3004': 0.878, '2010F4001': 0.797, '2010F4002': 0.854, '2010F4003': 0.864, '2010F4004': 0.829, '2010F4005': 0.826, '2010F4006': 0.802, '2010F5001': 0.646, '2010F5002': 0.647, '2010F5003': 0.855, '2010M2001': 0.828, '2010M2003': 0.742, '2010M2004': 0.939, '2010M2005': 0.731, '2010M2006': 0.929, '2010M3001': 0.894, '2010M3002': 0.866, '2010M3003': 0.866, '2010M3004': 0.614, '2010M3005': 0.68, '2010M3006': 0.544, '2010M4001': 0.917, '2010M4002': 0.859, '2010M4003': 0.794, '2010M5001': 0.845, '2010M5002': 0.614, '2010M6001': 0.924}}
{'config': {'annot': 'TS', 'label': 'ternary', 'modal': 'a', 'pmode': 8}, 'results': {'2010F2002': 0.869, '2010F2003': 0.843, '2010F2004': 0.7, '2010F3001': 0.683, '2010F3002': 0.8, '2010F3003': 0.795, '2010F3004': 0.824, '2010F4001': 0.766, '2010F4002': 0.792, '2010F4003': 0.852, '2010F4004': 0.764, '2010F4005': 0.837, '2010F4006': 0.802, '2010F5001': 0.899, '2010F5002': 0.853, '2010F5003': 0.843, '2010M2001': 0.839, '2010M2003': 0.691, '2010M2004': 0.866, '2010M2005': 0.785, '2010M2006': 0.882, '2010M3001': 0.773, '2010M3002': 0.742, '2010M3003': 0.829, '2010M3004': 0.771, '2010M3005': 0.67, '2010M3006': 0.748, '2010M4001': 0.903, '2010M4002': 0.707, '2010M4003': 0.841, '2010M5001': 0.859, '2010M5002': 0.784, '2010M6001': 0.864}}
{'config': {'annot': 'TS', 'label': 'ternary', 'modal': 'tav', 'pmode': 5}, 'results': {'2010F2002': 0.857, '2010F2003': 0.784, '2010F2004': 0.725, '2010F3001': 0.644, '2010F3002': 0.633, '2010F3003': 0.872, '2010F3004': 0.878, '2010F4001': 0.844, '2010F4002': 0.854, '2010F4003': 0.889, '2010F4004': 0.846, '2010F4005': 0.826, '2010F4006': 0.802, '2010F5001': 0.848, '2010F5002': 0.853, '2010F5003': 0.867, '2010M2001': 0.851, '2010M2003': 0.732, '2010M2004': 0.927, '2010M2005': 0.742, '2010M2006': 0.918, '2010M3001': 0.848, '2010M3002': 0.835, '2010M3003': 0.854, '2010M3004': 0.786, '2010M3005': 0.699, '2010M3006': 0.67, '2010M4001': 0.889, '2010M4002': 0.87, '2010M4003': 0.81, '2010M5001': 0.887, '2010M5002': 0.739, '2010M6001': 0.833}}
{'config': {'annot': 'TS', 'label': 'ternary', 'modal': 't', 'pmode': 5}, 'results': {'2010F2002': 0.762, '2010F2003': 0.843, '2010F2004': 0.725, '2010F3001': 0.644, '2010F3002': 0.567, '2010F3003': 0.936, '2010F3004': 0.892, '2010F4001': 0.797, '2010F4002': 0.854, '2010F4003': 0.877, '2010F4004': 0.821, '2010F4005': 0.826, '2010F4006': 0.791, '2010F5001': 0.646, '2010F5002': 0.662, '2010F5003': 0.867, '2010M2001': 0.851, '2010M2003': 0.732, '2010M2004': 0.927, '2010M2005': 0.72, '2010M2006': 0.918, '2010M3001': 0.894, '2010M3002': 0.866, '2010M3003': 0.878, '2010M3004': 0.614, '2010M3005': 0.709, '2010M3006': 0.544, '2010M4001': 0.917, '2010M4002': 0.87, '2010M4003': 0.778, '2010M5001': 0.859, '2010M5002': 0.614, '2010M6001': 0.924}}
{'config': {'annot': 'TS', 'label': 'ternary', 'modal': 'tv', 'pmode': 7}, 'results': {'2010F2002': 0.762, '2010F2003': 0.863, '2010F2004': 0.688, '2010F3001': 0.663, '2010F3002': 0.578, '2010F3003': 0.923, '2010F3004': 0.878, '2010F4001': 0.812, '2010F4002': 0.844, '2010F4003': 0.852, '2010F4004': 0.78, '2010F4005': 0.859, '2010F4006': 0.791, '2010F5001': 0.646, '2010F5002': 0.676, '2010F5003': 0.819, '2010M2001': 0.885, '2010M2003': 0.732, '2010M2004': 0.927, '2010M2005': 0.72, '2010M2006': 0.929, '2010M3001': 0.894, '2010M3002': 0.856, '2010M3003': 0.866, '2010M3004': 0.614, '2010M3005': 0.68, '2010M3006': 0.553, '2010M4001': 0.903, '2010M4002': 0.88, '2010M4003': 0.667, '2010M5001': 0.887, '2010M5002': 0.432, '2010M6001': 0.924}}
{'config': {'annot': 'TS', 'label': 'ternary', 'modal': 'tv', 'pmode': 6}, 'results': {'2010F2002': 0.762, '2010F2003': 0.863, '2010F2004': 0.712, '2010F3001': 0.644, '2010F3002': 0.556, '2010F3003': 0.936, '2010F3004': 0.878, '2010F4001': 0.797, '2010F4002': 0.865, '2010F4003': 0.864, '2010F4004': 0.829, '2010F4005': 0.826, '2010F4006': 0.802, '2010F5001': 0.646, '2010F5002': 0.647, '2010F5003': 0.855, '2010M2001': 0.828, '2010M2003': 0.742, '2010M2004': 0.951, '2010M2005': 0.731, '2010M2006': 0.929, '2010M3001': 0.894, '2010M3002': 0.866, '2010M3003': 0.866, '2010M3004': 0.614, '2010M3005': 0.68, '2010M3006': 0.544, '2010M4001': 0.917, '2010M4002': 0.87, '2010M4003': 0.794, '2010M5001': 0.845, '2010M5002': 0.614, '2010M6001': 0.924}}
{'config': {'annot': 'TS', 'label': 'ternary', 'modal': 'ta', 'pmode': 5}, 'results': {'2010F2002': 0.857, '2010F2003': 0.775, '2010F2004': 0.725, '2010F3001': 0.644, '2010F3002': 0.633, '2010F3003': 0.897, '2010F3004': 0.892, '2010F4001': 0.828, '2010F4002': 0.854, '2010F4003': 0.889, '2010F4004': 0.846, '2010F4005': 0.826, '2010F4006': 0.802, '2010F5001': 0.848, '2010F5002': 0.853, '2010F5003': 0.843, '2010M2001': 0.862, '2010M2003': 0.732, '2010M2004': 0.927, '2010M2005': 0.742, '2010M2006': 0.929, '2010M3001': 0.864, '2010M3002': 0.825, '2010M3003': 0.866, '2010M3004': 0.771, '2010M3005': 0.718, '2010M3006': 0.68, '2010M4001': 0.889, '2010M4002': 0.88, '2010M4003': 0.81, '2010M5001': 0.887, '2010M5002': 0.75, '2010M6001': 0.833}}
{'config': {'annot': 'TS', 'label': 'ternary', 'modal': 'v', 'pmode': 4}, 'results': {'2010F2002': 0.75, '2010F2003': 0.804, '2010F2004': 0.625, '2010F3001': 0.663, '2010F3002': 0.7, '2010F3003': 0.756, '2010F3004': 0.865, '2010F4001': 0.781, '2010F4002': 0.719, '2010F4003': 0.778, '2010F4004': 0.577, '2010F4005': 0.772, '2010F4006': 0.523, '2010F5001': 0.747, '2010F5002': 0.765, '2010F5003': 0.651, '2010M2001': 0.793, '2010M2003': 0.639, '2010M2004': 0.793, '2010M2005': 0.624, '2010M2006': 0.894, '2010M3001': 0.636, '2010M3002': 0.68, '2010M3003': 0.72, '2010M3004': 0.671, '2010M3005': 0.602, '2010M3006': 0.718, '2010M4001': 0.778, '2010M4002': 0.783, '2010M4003': 0.714, '2010M5001': 0.676, '2010M5002': 0.545, '2010M6001': 0.833}}
{'config': {'annot': 'TS', 'label': 'ternary', 'modal': 'av', 'pmode': 4}, 'results': {'2010F2002': 0.893, '2010F2003': 0.765, '2010F2004': 0.738, '2010F3001': 0.693, '2010F3002': 0.756, '2010F3003': 0.859, '2010F3004': 0.851, '2010F4001': 0.828, '2010F4002': 0.781, '2010F4003': 0.852, '2010F4004': 0.748, '2010F4005': 0.826, '2010F4006': 0.767, '2010F5001': 0.899, '2010F5002': 0.868, '2010F5003': 0.831, '2010M2001': 0.874, '2010M2003': 0.649, '2010M2004': 0.866, '2010M2005': 0.742, '2010M2006': 0.906, '2010M3001': 0.833, '2010M3002': 0.742, '2010M3003': 0.854, '2010M3004': 0.729, '2010M3005': 0.631, '2010M3006': 0.709, '2010M4001': 0.833, '2010M4002': 0.75, '2010M4003': 0.825, '2010M5001': 0.887, '2010M5002': 0.807, '2010M6001': 0.848}}
{'config': {'annot': 'TS', 'label': 'ternary', 'modal': 'v', 'pmode': 6}, 'results': {'2010F2002': 0.667, '2010F2003': 0.667, '2010F2004': 0.55, '2010F3001': 0.317, '2010F3002': 0.489, '2010F3003': 0.474, '2010F3004': 0.703, '2010F4001': 0.609, '2010F4002': 0.698, '2010F4003': 0.642, '2010F4004': 0.374, '2010F4005': 0.728, '2010F4006': 0.488, '2010F5001': 0.671, '2010F5002': 0.574, '2010F5003': 0.59, '2010M2001': 0.621, '2010M2003': 0.454, '2010M2004': 0.659, '2010M2005': 0.602, '2010M2006': 0.859, '2010M3001': 0.576, '2010M3002': 0.629, '2010M3003': 0.695, '2010M3004': 0.643, '2010M3005': 0.427, '2010M3006': 0.621, '2010M4001': 0.625, '2010M4002': 0.728, '2010M4003': 0.667, '2010M5001': 0.521, '2010M5002': 0.432, '2010M6001': 0.788}}
{'config': {'annot': 'TS', 'label': 'ternary', 'modal': 'av', 'pmode': 6}, 'results': {'2010F2002': 0.833, '2010F2003': 0.725, '2010F2004': 0.675, '2010F3001': 0.317, '2010F3002': 0.733, '2010F3003': 0.821, '2010F3004': 0.689, '2010F4001': 0.797, '2010F4002': 0.781, '2010F4003': 0.852, '2010F4004': 0.715, '2010F4005': 0.783, '2010F4006': 0.756, '2010F5001': 0.873, '2010F5002': 0.882, '2010F5003': 0.687, '2010M2001': 0.736, '2010M2003': 0.68, '2010M2004': 0.72, '2010M2005': 0.677, '2010M2006': 0.894, '2010M3001': 0.697, '2010M3002': 0.722, '2010M3003': 0.768, '2010M3004': 0.743, '2010M3005': 0.534, '2010M3006': 0.67, '2010M4001': 0.819, '2010M4002': 0.728, '2010M4003': 0.778, '2010M5001': 0.873, '2010M5002': 0.795, '2010M6001': 0.788}}
{'config': {'annot': 'TS', 'label': 'ternary', 'modal': 'a', 'pmode': 4}, 'results': {'2010F2002': 0.929, '2010F2003': 0.725, '2010F2004': 0.75, '2010F3001': 0.733, '2010F3002': 0.756, '2010F3003': 0.859, '2010F3004': 0.865, '2010F4001': 0.828, '2010F4002': 0.792, '2010F4003': 0.864, '2010F4004': 0.805, '2010F4005': 0.815, '2010F4006': 0.756, '2010F5001': 0.911, '2010F5002': 0.868, '2010F5003': 0.783, '2010M2001': 0.874, '2010M2003': 0.691, '2010M2004': 0.829, '2010M2005': 0.72, '2010M2006': 0.894, '2010M3001': 0.818, '2010M3002': 0.742, '2010M3003': 0.841, '2010M3004': 0.771, '2010M3005': 0.65, '2010M3006': 0.728, '2010M4001': 0.819, '2010M4002': 0.707, '2010M4003': 0.857, '2010M5001': 0.901, '2010M5002': 0.773, '2010M6001': 0.833}}
{'config': {'annot': 'TS', 'label': 'ternary', 'modal': 'v', 'pmode': 8}, 'results': {'2010F2002': 0.798, '2010F2003': 0.667, '2010F2004': 0.55, '2010F3001': 0.317, '2010F3002': 0.7, '2010F3003': 0.474, '2010F3004': 0.892, '2010F4001': 0.75, '2010F4002': 0.74, '2010F4003': 0.728, '2010F4004': 0.374, '2010F4005': 0.783, '2010F4006': 0.547, '2010F5001': 0.747, '2010F5002': 0.779, '2010F5003': 0.663, '2010M2001': 0.828, '2010M2003': 0.454, '2010M2004': 0.768, '2010M2005': 0.634, '2010M2006': 0.847, '2010M3001': 0.621, '2010M3002': 0.691, '2010M3003': 0.695, '2010M3004': 0.686, '2010M3005': 0.427, '2010M3006': 0.621, '2010M4001': 0.75, '2010M4002': 0.783, '2010M4003': 0.762, '2010M5001': 0.704, '2010M5002': 0.432, '2010M6001': 0.833}}

       t      a      v     ta     tv     av    tav
0  0.000  0.000  0.000  0.000  0.000  0.000  0.000
1  0.000  0.000  0.000  0.000  0.000  0.000  0.000
2  0.000  0.000  0.000  0.000  0.000  0.000  0.000
3  0.000  0.000  0.000  0.000  0.000  0.000  0.000
4  0.741  0.751  0.675  0.755  0.733  0.742  0.768
5  0.739  0.694  0.524  0.756  0.739  0.696  0.751
6  0.740  0.691  0.524  0.753  0.740  0.672  0.752
7  0.706  0.664  0.662  0.694  0.706  0.642  0.699
8  0.731  0.750  0.540  0.766  0.730  0.742  0.767

50歳以上

       t      a      v     ta     tv     av    tav
0  0.000  0.000  0.000  0.000  0.000  0.000  0.000
1  0.000  0.000  0.000  0.000  0.000  0.000  0.000
2  0.000  0.000  0.000  0.000  0.000  0.000  0.000
3  0.000  0.000  0.000  0.000  0.000  0.000  0.000
4  0.808  0.825  0.732  0.848  0.813  0.827  0.853
5  0.815  0.799  0.633  0.844  0.814  0.776  0.844
6  0.811  0.802  0.633  0.842  0.813  0.775  0.842
7  0.812  0.796  0.731  0.834  0.814  0.778  0.840
8  0.814  0.825  0.724  0.851  0.820  0.839  0.858